export const SEARCH_INPUT_CHANGE = 'REPO/SEARCH_INPUT_CHANGE';
export const REPO_LIST_REQUESTED = 'REPO/REPO_LIST_REQUESTED';
export const REPO_LIST_SUCCESS = 'REPO/REPO_LIST_SUCCESS';
export const REPO_LIST_FAIL = 'REPO/REPO_LIST_FAIL';
export const REPO_SELECT = 'REPO/REPO_SELECT';
