export const SEARCH_INPUT_CHANGE = 'REPO/SEARCH_INPUT_CHANGE';
export const FILTER_REPO_LIST = 'REPO/FILTER_REPO_LIST';
export const REPO_SELECT = 'REPO/REPO_SELECT';

export const REPO_LIST_REQUESTED = 'REPO/REPO_LIST_REQUESTED';
export const REPO_LIST_SUCCESS = 'REPO/REPO_LIST_SUCCESS';
export const REPO_LIST_FAIL = 'REPO/REPO_LIST_FAIL';

export const SAVE_REPO_REQUESTED = 'REPO/SAVE_REPO_REQUESTED';
export const SAVE_REPO_SUCCESS = 'REPO/SAVE_REPO_SUCCESS';
export const SAVE_REPO_FAIL = 'REPO/SAVE_REPO_FAIL';
